services:
  api-gateway-service:
    build:
      context: ./api-gateway-service
    ports:
      - 8080:8080
    networks:
      - app-network
  wiki-service:
    build:
      context: ./wiki-service
    ports:
      - 8081:8081
    networks:
      - app-network
  entry-service:
    build:
      context: ./entry-service
    ports:
      - 8082:8082
    networks:
      - app-network
  comment-service:
    build:
      context: ./comment-service
    ports:
      - 8083:8083
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
